use_frameworks!

target 'LookinDemoSwift' do
#    pod 'LookinServer', :subspecs => ['Swift'], :configurations => ['Debug']
    
    pod 'LookinServer', :path=>'../../', :configurations => ['Debug']
end
